name: THRPlugin
description: HEY HEY :D
main: ml.chromaryu.Touhouraces.THRPlugin
author: noteumaple,Tanikyan,Chromaryu
version: 1.1
commands:
   touhouraces:
      description: Version
   thr:
      description: Version and shortcut